[package]
name = "interrupt-mutex"
version = "0.1.0"
edition = "2021"
description = "A mutex for sharing data with interrupt handlers."
repository = "https://github.com/mkroening/interrupt-mutex"
license = "MIT OR Apache-2.0"
keywords = ["interrupts", "disable", "without"]
categories = ["no-std::no-alloc"]

[dependencies]
interrupts = "0.2"
lock_api = "0.4"

[dev-dependencies]
parking_lot = "0.12"
